run:
  issues-exit-code: 2
linters:
  enable:
  - godot
  - goimports
  - gofmt
  - ginkgolinter
  - dogsled
  - copyloopvar
  - gocritic
  - misspell
  - nolintlint
  - stylecheck
  - unconvert
  - unparam
  - whitespace
  - revive
  - unused
  - wastedassign
linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log
  godot:
    scope: toplevel
    capital: true
    exclude:
    - 'SPDX-License-Identifier.*'
    - '\+groupName.*'
  misspell:
    locale: US
    ignore-words:
      - neighbours
      - neighbour
  stylecheck:
    dot-import-whitelist:
    - github.com/onsi/ginkgo
    - github.com/onsi/gomega
  gocritic:
    disabled-checks:
      - captLocal
      - exitAfterDefer
  revive:
    rules:
    - name: receiver-naming
      disabled: true
    - name: dot-imports
      disabled: true
issues:
  exclude-rules:
    - path: 'api'
      linters:
        - stylecheck
