run:
  issues-exit-code: 2
linters:
  enable:
  - godot
  - goimports
  - gofmt
  - ginkgolinter
  - dogsled
  #- exportloopref        #bugs
  #- goconst              #stye  - fixes required
  - gocritic             #style - fixes required
  #- gomnd                #style - fixes required
  - misspell             #style - fixes required
  - nolintlint
  - stylecheck
  - unconvert
  - unparam              # still 1 fix
  - whitespace
linters-settings:
  errcheck:
    exclude: .golangci.exclude
  godot:
    scope: toplevel
    capital: true
    exclude:
    - 'SPDX-License-Identifier.*'
    - '\+groupName.*'
  exhaustive:
    ignore-enum-types: "syscall.Errno.+"
    check:
      - switch
      - map
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
    ignore-words:
      - neighbours
      - neighbour
  stylecheck:
    dot-import-whitelist:
    - github.com/onsi/ginkgo
    - github.com/onsi/gomega
  gocritic:
    disabled-checks:
      - captLocal
      - exitAfterDefer
issues:
  exclude-rules:
    - path: '/api'
    linters:
      - stylecheck
