version: "2"
run:
  issues-exit-code: 2
linters:
  enable:
    - copyloopvar
    - dogsled
    - ginkgolinter
    - gocritic
    - godot
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
    gocritic:
      disabled-checks:
        - captLocal
        - exitAfterDefer
    godot:
      scope: toplevel
      exclude:
        - SPDX-License-Identifier.*
        - \+groupName.*
      capital: true
    misspell:
      locale: US
      ignore-rules:
        - neighbours
        - neighbour
    revive:
      rules:
        - name: receiver-naming
          disabled: true
        - name: dot-imports
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: api
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
