apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests.yaml
- service.yaml
- secret.yaml

configurations:
- kustomizeconfig.yaml

patches:
- path: patches/patch_webhook_configuration.yaml
  target:
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
    version: v1
