apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- exclude-l2-config.yaml
- ../crd
- ../rbac
- ../controllers
- ../webhook
# Uncomment to install network policies
#- ../networkpolicies
namespace: metallb-system
