- op: add
  path: "/rules/-"
  value:
    apiGroups: 
      - admissionregistration.k8s.io
    resources: 
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

- op: add
  path: "/rules/-"
  value:
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
