apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: controller
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        env:
        - name: ENABLE_OPERATOR_WEBHOOK
          value: "true"
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
