apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition 
metadata:
  annotations:                 
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  name: addresspools.metallb.io
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition 
metadata:
  annotations:                 
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  name: bgppeers.metallb.io
