name: Site Build 

on:
  pull_request:
    paths:
      - 'website/**'
      - 'netlify.toml'
    branches:
      - "main"
      - "v**"
  workflow_dispatch:

jobs:
  validate-website-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: wagoid/commitlint-github-action@v5
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.124.1'

      - name: Build
        run: cd ./website && hugo
