{{- if .Values.controller.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metallb.controller.serviceAccountName" . }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
{{- with .Values.imagePullSecrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .Values.privateRegistry.registrySecret }}
  - name: {{ .Values.privateRegistry.registrySecret }}
{{- end }}
{{- end }}
{{- if .Values.speaker.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metallb.speaker.serviceAccountName" . }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: speaker
  {{- with .Values.speaker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
{{- with .Values.imagePullSecrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .Values.privateRegistry.registrySecret }}
  - name: {{ .Values.privateRegistry.registrySecret }}
{{- end }}
{{- end }}
